### ISSUE TITLE
Feedback from Sylvia and Birinder

### ISSUE THREAD

**Issue by LeeYinYing** [UBC-MDS/violent_crimes_usa#13]
- Specify in the map whether each circle is the total number of crime incident or it is one circle for each type of crime
- If no type of the crime is selected, the map breaks...
- Graphs are on different scales, this is hard for comparison
- Perhaps set bounds for limiting the map to just the US
- Maybe use color scale to show magnitude in the map instead of of circle size
- Make 4 plots into one, then put the map and the plot side by side so you don't need to scroll. 
- Like how you guys have description at the top of the selection panel, but maybe have it as a subtitle until the title. Some may mistaken it for selection instructions.

**Comment by alyciakb** [comment]
Thank you for the feedback!

We implemented the following changes:
- Added a readable error message when no crime type is selected
- Set bounds on the map
- Used a colour scale instead of circle size on the map
- Merged the four plots into one plot
- Moved the description in the selection panel to be a title for the plot
